### ISSUE TITLE
Installation documentation improvements

### ISSUE THREAD

**Issue by DavidWittman** [skuid/helm-value-store#4]
After reading through the documentation and most of the code, it's still not obvious to me how to create the DynamoDB table for storing my Helm values 🙁 . It looks like the `load` subcommand is what I should be using to create the table, but this accepts "a json file of releases", and I'm not quite sure how to generate that from Helm.

There's some chance I'm just being dense, but it would be nice to have some more specific information in the README with regard to how to get this working from scratch.

Thanks!

**Comment by micahhausler** [comment]
Hi David
